### ISSUE TITLE
Describe icon usage

### ISSUE THREAD

**Issue by FaBjE** [spencerwmiles/vscode-task-buttons#15]
Looking to implement the placement of an icon in the button I discovered this is already possible.
using the $(icon-name) syntax.
The names of the possible icons are listed here: https://code.visualstudio.com/api/references/icons-in-labels#icon-listing

Example:
`"label": "$(notebook-move-down) [Debug] Build",`

I can add a little description to the readme.md if desired?

**Comment by spencerwmiles** [comment]
That would be great!

It might make sense to show that it's possible to use emojis for labels while you are there. [example](https://github.com/spencerwmiles/vscode-task-buttons/issues/7). 

Apologies for the slow replies, I plan on coming back to this project and doing some cleanup but I have been really busy as of late.

Appreciate your efforts pal.

**Comment by FaBjE** [comment]
I did not know you can also add emoji's. I made a pull request with the changes
https://github.com/spencerwmiles/vscode-task-buttons/pull/19

No worries about the reply times. We are half a world apart anyway (time difference...)
