### ISSUE TITLE
Improve workspace compatibility

### ISSUE THREAD

**Issue by spencerwmiles** [spencerwmiles/vscode-task-buttons#16]
Figure out and implement what is necessary to get Task Buttons to load project level settings (and therefore task buttons configuration) when viewing a file, etc. within a project that may have it's own Task Buttons configuration.

Determine correct load order (Project -> Workspace -> User?) and implement a solution that solves all cases and try not to impact existing functionality. 

It may make sense to leverage some of what was done for https://github.com/spencerwmiles/vscode-task-buttons/pull/8 to reduce the amount

**Comment by FaBjE** [comment]
This is already handled/provided for by vscode.
You can define a settings.json at project level.

I made a pull request adding a little test workspace to the repository using this:
https://github.com/spencerwmiles/vscode-task-buttons/pull/18

**Comment by spencerwmiles** [comment]
@FaBjE 

Appreciate your efforts.

I'll look at this over the weekend and hopefully get a new release out as well.
