### ISSUE TITLE
Allow for dropdown menus

### ISSUE THREAD

**Issue by spencerwmiles** [spencerwmiles/vscode-task-buttons#2]
This could allow for more tasks to be added and organized by a common type.

Example:
-     AWS
-         EC2 Start
-         EC2 Shutdown

**Comment by gameguy682** [comment]
Going to reopen this as the development branch is stale and is most likely going to be removed in the future. I redid the PR and pointed it towards the production branch in #20

**Comment by spencerwmiles** [comment]
@gameguy682 I'll take a look at over the weekend.

**Comment by spencerwmiles** [comment]
Will be release in V1.1.0. thanks again @[gameguy682](https://github.com/gameguy682) gameguy682
