### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by gameguy682** [spencerwmiles/vscode-task-buttons#22]
These PRs are currently pending on being released:

- #17 
- #19 

Lets update this when PRs get merged in.

**Comment by gameguy682** [comment]
@spencerwmiles When you do make the next version, use this (and any other PRs you merged in) as a reference to update the changelog. Also, be sure to update the CHANGELOG.md file too, as that's out of date.

**Comment by spencerwmiles** [comment]
Sorry I dropped the ball a bit with the PRs and merges. Everything should be included in V1.1.0
