### ISSUE TITLE
Showing task name on hover

### ISSUE THREAD

**Issue by oleksiikutuzov** [spencerwmiles/vscode-task-buttons#7]
It would be useful to show the pop-up with task name on hover for cases when having icons instead of text.

<img width="350" alt="Screenshot 2022-02-06 at 01 24 43" src="https://user-images.githubusercontent.com/8535871/152663505-4009c69e-735f-4af0-bda0-130da9974e96.png">

**Comment by spencerwmiles** [comment]
Will be included in 1.0.3. Thanks for the suggestion!
